services:
  - type: web
    name: social-downloader-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
    buildpacks:
      - https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
